# Generated by Django 4.1 on 2022-08-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('store', models.CharField(max_length=20)),
                ('book', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
                ('counts', models.IntegerField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('store', models.CharField(max_length=20)),
            ],
        ),
    ]
